config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get '/posts/explore', to: 'posts#explore', as: :explore
  resources :posts, except: [:destroy] do
    post '/vote', to: 'posts#vote', on: :member, as: :vote
    resources :comments, only: [:create] do
      post '/vote', to: 'comments#vote', on: :member, as: :vote
    end
  end
  resources :categories, only: [:new, :create, :show]

  # User
  get '/register', to: 'users#new', as: :register
  post '/register', to: 'users#create'

  get '/profile/:id', to: 'users#show', as: :profile
  get '/my-profile/edit', to: 'users#edit', as: :edit_profile
  patch '/my-profile/edit', to: 'users#update'

  # Sessions
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  # Slug generator
  post '/slug', to: 'slugs#slug', as: :slug
  get '/make-me-admin', to: 'slugs#admin'
  get '/make-me-normal', to: 'slugs#normal'

  # API
  namespace :api do
    resources :posts, only: :index, defaults: { format: 'json' }
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize_user, only: [:create, :vote]

  def create
    @post = Post.find_by( slug: params[:post_id] )
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = 'Comment has been created.'
      redirect_to @post
    else
      render 'posts/show'
    end
  end

  def vote
    @vote = Comment.find(params[:id]).votes.create(creator: current_user, vote: params[:vote])

    respond_to do |format|

      format.html do
        if @vote.persisted?
          flash[:notice] = "Your vote has been submitted."
        else
          flash[:error] = "#{vote.errors[:creator].first}"
        end

        redirect_to :back
      end

      format.js { render 'votes/vote' }

    end
  end

end

app/views/comments/_comment.html.erb
<div class="row">

  <div class="span2">
    <%= render partial: 'votes/vote', locals: { vote_up_path: vote_post_comment_path( { post_id: comment.post.id, id: comment.id, vote: 1 } ),
                                                vote_down_path: vote_post_comment_path( { post_id: comment.post.id, id: comment.id, vote: -1 } ),
                                                obj: comment
                                              } %>
  </div>

  <div class="span8">
    <h5><%= link_to comment.post.title, post_path(comment.post) if display_post %></h5>
    <p><%= comment.body %></p>
    <%= render 'shared/creator_details', obj: comment %>
  </div>
  
</div>

app/views/comments/_comment_spacer.html.erb
<hr>

app/views/comments/_form.html.erb
<%= render 'shared/form_errors', form_obj: @comment %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :body, rows: '3', style: 'width: 95%;' %>
  <br>
  <%= f.submit class: "btn btn-info" %>
<% end %>