config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get '/posts/explore', to: 'posts#explore', as: :explore
  resources :posts, except: [:destroy] do
    post '/vote', to: 'posts#vote', on: :member, as: :vote
    resources :comments, only: [:create] do
      post '/vote', to: 'comments#vote', on: :member, as: :vote
    end
  end
  resources :categories, only: [:new, :create, :show]

  # User
  get '/register', to: 'users#new', as: :register
  post '/register', to: 'users#create'

  get '/profile/:id', to: 'users#show', as: :profile
  get '/my-profile/edit', to: 'users#edit', as: :edit_profile
  patch '/my-profile/edit', to: 'users#update'

  # Sessions
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  # Slug generator
  post '/slug', to: 'slugs#slug', as: :slug
  get '/make-me-admin', to: 'slugs#admin'
  get '/make-me-normal', to: 'slugs#normal'

  # API
  namespace :api do
    resources :posts, only: :index, defaults: { format: 'json' }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :url, presence: true

  has_slug :title
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    def index
      @posts = Post.all

      respond_to do |format|
        format.json { render json: @posts }
        format.xml { render xml: @posts }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :authorize_user, only: [:create, :edit, :new, :update, :vote]
  before_action :allow_edit_update, only: [:edit, :update]


  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post has been created."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post has been updated."
      redirect_to post_path(params[:id])
    else
      render :edit
    end
  end

  def explore; end

  def vote
    @vote = Post.find(params[:id]).create_vote( { creator: current_user, vote: params[:vote] } )

    respond_to do |format|

      format.html do
        if @vote.persisted?
          flash[:notice] = "Your vote has been submitted."
        else
          flash[:error] = "#{vote.errors[:creator].first}"
        end
        redirect_to :back
      end

      format.js { render 'votes/vote' }

    end

  end

  private
    def set_post
      @post = Post.find_by(slug: params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :description, category_ids: [])
    end

    def allow_edit_update
      unless allowed_to_edit_update? @post
        flash[:error] = "You are not allowed to edit this post"
        redirect_to root_path
      end
    end
end

app/views/posts/_form.html.erb
<%= render 'shared/form_errors', form_obj: @post %>

<div class="row">
  <div class="span6 well">
    <%= form_for @post do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :url %>
      <%= f.text_field :url %>

      <br>

      <%= f.label :category_ids, 'Category' %>
      <%= f.select :category_ids, Category.all.map { |c| [ c.name, c.id ] }, {}, { multiple: 'multiple', size: "#{Category.all.size}" } %>

      <br>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <hr>

      <%= f.submit class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="span2">
  <%= render partial: 'votes/vote', locals: { vote_up_path: vote_post_path({ id: post.id, vote: 1 }),
                                              vote_down_path: vote_post_path({ id: post.id, vote: -1 }),
                                              obj: post
                                            } %>
  </div>

  <div class="span7 well">

    <%= render post.categories %>

    <h4><%= link_to post.title, post_path(post) %> &nbsp;&nbsp;&nbsp;<small><%= link_to 'View Site', fix_url(post.url) %></small> </h4>
    <p><%= post.description %></p>

    <%= render 'shared/creator_details', obj: post %>

    <small>
      <span>
        <%= link_to "#{post.comments.size} #{"comment".pluralize(post.comments.size)}", post_path(post) %>
      </span>
      <% if allowed_to_edit_update? post %>
        <span>
          <%= link_to "(Edit)", edit_post_path(post) %>
        </span>
      <% end %>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>
<%= render 'form' %>

<hr>

<div class="row">
  <div class="span12">
    <small><%= link_to 'Back to All Posts', posts_path %></small>
  </div>
</div>

app/views/posts/explore.html.erb
<h4>Explore Non Model Backed Form Helpers</h4>

<%= form_tag explore_path, method: 'get' do %>
<div class="row">
  <div class="span6 well">
    <%= label_tag :name, 'Name: ' %>
    <%= text_field_tag :name %>
    <br>
    <div style="display: flex;">
      <%= radio_button_tag :gender, 'male' %> &nbsp; <%= label_tag :gender_male, 'Male' %>
    </div>
    <div style="display: flex;">
      <%= radio_button_tag :gender, 'female' %> &nbsp; <%= label_tag :gender_female, 'Female' %>
    </div>
    <br>
    <%= label_tag :user_phone, 'Phone: ' %>
    <%= telephone_field(:user, :phone) %>
    <br>
    <%= select_tag(:city_id, options_for_select([['Libson', 1],['Madrid', 2],['Boston', 3],['New York', 4],['California', 5]], 3)) %>
    <br>
    <%= collection_select(:post, :category_id, Category.all, :id, :name) %>
      <%= time_zone_select(:post, :time_zone) %>
      <%= select_date Date.today, prefix: :post %>

    <hr>

    <%= submit_tag 'Submit', class: 'btn btn-block btn-success' %>

  </div>
</div>
<% end %>

<h4>Explore Model Based Form Helper for Select</h4>
<%= form_for Post.new do |f| %>
  <div class="row">
    <div class="span6 well">
      <%= f.label :category %>
      <%= date_select :person, :birth_date %>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= render 'shared/content_title' %>

<div class="row">
  <div class="span10">
    <%= render(@posts) || "No posts available as of now." %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create New Post' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'shared/content_title', title: "Post: #{@post.title}" %>

<p>
  <%= render @post.categories %>
</p>

<p><strong>URL: </strong><%= link_to @post.url, fix_url(@post.url) %></p>
<p><strong>Description: </strong><%= @post.description %></p>

<br>

<small>
  <%= link_to('Edit', edit_post_path(@post)) if allowed_to_edit_update? @post %>
  <%= '|' if allowed_to_edit_update? @post %>
  <%= link_to 'Back to All Posts', posts_path %>
</small>

<hr/>

<h4>Comments</h4>

<div class="row">
  <div class="span10 well">
    <% if current_user %>
      <h6>Create Comment</h6>
      <%= render 'comments/form' %>
      <hr>
    <% end %>

    <%= render(partial: 'comments/comment', collection: @post.comments.order("created_at DESC"), locals: { display_post: false }, spacer_template: 'comments/comment_spacer') || 'No comments for post.' %>
  </div>
</div>