config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get '/posts/explore', to: 'posts#explore', as: :explore
  resources :posts, except: [:destroy] do
    post '/vote', to: 'posts#vote', on: :member, as: :vote
    resources :comments, only: [:create] do
      post '/vote', to: 'comments#vote', on: :member, as: :vote
    end
  end
  resources :categories, only: [:new, :create, :show]

  # User
  get '/register', to: 'users#new', as: :register
  post '/register', to: 'users#create'

  get '/profile/:id', to: 'users#show', as: :profile
  get '/my-profile/edit', to: 'users#edit', as: :edit_profile
  patch '/my-profile/edit', to: 'users#update'

  # Sessions
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  # Slug generator
  post '/slug', to: 'slugs#slug', as: :slug
  get '/make-me-admin', to: 'slugs#admin'
  get '/make-me-normal', to: 'slugs#normal'

  # API
  namespace :api do
    resources :posts, only: :index, defaults: { format: 'json' }
  end
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="span12">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class="nav-item">
  <% if logged_in? %>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-small btn-primary' %>
  <% end %>

  <div class="btn-group">
    <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
      Categories
      <span class="caret"></span>
    </a>

    <ul class="dropdown-menu">
      <% if Category.all.empty? %>
        <li><%= link_to "No Categories Available", '#' %></li>
      <% end %>
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
      <% if logged_in? %>
        <li class="divider"></li>
        <li>
          <%= link_to new_category_path do %>
            <i class="icon-plus"></i> New Category
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="pull-right">
    <% if logged_in? %>
      
      <div class="btn-group">
        <a class="btn btn-small btn-info dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user icon-white"></i>
          <%= current_user.username %>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu">
          <li>
            <%= link_to profile_path(current_user) do %>
              <i class="icon-th-large"></i> View Profile
            <% end %>
          </li>
          <li>
            <%= link_to edit_profile_path do %>
              <i class="icon-pencil"></i> Edit Profile
            <% end %>
          </li>
          <% if current_user.admin? %>
            <li>
              <%= link_to slug_path, method: 'post', confirm: 'Are you sure you want to generate all slugs?' do %>
                <i class="icon-warning-sign"></i> Generate Slug
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

      <%= link_to 'Logout', logout_path, class: 'btn btn-small btn-danger', method: :delete %>

    <% else %>

      <%= link_to 'Register', register_path, class: 'btn btn-small btn-info' %>
      <%= link_to 'Login', login_path, class: 'btn btn-small btn-success' %>

    <% end %>
  </div>  
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>